fn main() {
    println!("Hello, world!");
}
pub enum Element {
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og,
}
pub fn to_string(element: Element) -> String {
    String::from(match element {
        Element::H => "Hydrogen",
        Element::He => "Helium",
        Element::Li => "Lithium",
        Element::Be => "Beryllium",
        Element::B => "Boron",
        Element::C => "Carbon",
        Element::N => "Nitrogen",
        Element::O => "Oxygen",
        Element::F => "Fluorine",
        Element::Ne => "Neon",
        Element::Na => "Sodium",
        Element::Mg => "Magnesium",
        Element::Al => "Aluminum",
        Element::Si => "Silicon",
        Element::P => "Phosphorus",
        Element::S => "Sulfur",
        Element::Cl => "Chlorine",
        Element::Ar => "Argon",
        Element::K => "Potassium",
        Element::Ca => "Calcium",
        Element::Sc => "Scandium",
        Element::Ti => "Titanium",
        Element::V => "Vanadium",
        Element::Cr => "Chromium",
        Element::Mn => "Manganese",
        Element::Fe => "Iron",
        Element::Co => "Cobalt",
        Element::Ni => "Nickel",
        Element::Cu => "Copper",
        Element::Zn => "Zinc",
        Element::Ga => "Gallium",
        Element::Ge => "Germanium",
        Element::As => "Arsenic",
        Element::Se => "Selenium",
        Element::Br => "Bromine",
        Element::Kr => "Krypton",
        Element::Rb => "Rubidium",
        Element::Sr => "Strontium",
        Element::Y => "Yttrium",
        Element::Zr => "Zirconium",
        Element::Nb => "Niobium",
        Element::Mo => "Molybdenum",
        Element::Tc => "Technetium",
        Element::Ru => "Ruthenium",
        Element::Rh => "Rhodium",
        Element::Pd => "Palladium",
        Element::Ag => "Silver",
        Element::Cd => "Cadmium",
        Element::In => "Indium",
        Element::Sn => "Tin",
        Element::Sb => "Antimony",
        Element::Te => "Tellurium",
        Element::I => "Iodine",
        Element::Xe => "Xenon",
        Element::Cs => "Cesium",
        Element::Ba => "Barium",
        Element::La => "Lanthanum",
        Element::Ce => "Cerium",
        Element::Pr => "Praseodymium",
        Element::Nd => "Neodymium",
        Element::Pm => "Promethium",
        Element::Sm => "Samarium",
        Element::Eu => "Europium",
        Element::Gd => "Gadolinium",
        Element::Tb => "Terbium",
        Element::Dy => "Dysprosium",
        Element::Ho => "Holmium",
        Element::Er => "Erbium",
        Element::Tm => "Thulium",
        Element::Yb => "Ytterbium",
        Element::Lu => "Lutetium",
        Element::Hf => "Hafnium",
        Element::Ta => "Tantalum",
        Element::W => "Wolfram",
        Element::Re => "Rhenium",
        Element::Os => "Osmium",
        Element::Ir => "Iridium",
        Element::Pt => "Platinum",
        Element::Au => "Gold",
        Element::Hg => "Mercury",
        Element::Tl => "Thallium",
        Element::Pb => "Lead",
        Element::Bi => "Bismuth",
        Element::Po => "Polonium",
        Element::At => "Astatine",
        Element::Rn => "Radon",
        Element::Fr => "Francium",
        Element::Ra => "Radium",
        Element::Ac => "Actinium",
        Element::Th => "Thorium",
        Element::Pa => "Protactinium",
        Element::U => "Uranium",
        Element::Np => "Neptunium",
        Element::Pu => "Plutonium",
        Element::Am => "Americium",
        Element::Cm => "Curium",
        Element::Bk => "Berkelium",
        Element::Cf => "Californium",
        Element::Es => "Einsteinium",
        Element::Fm => "Fermium",
        Element::Md => "Mendelevium",
        Element::No => "Nobelium",
        Element::Lr => "Lawrencium",
        Element::Rf => "Rutherfordium",
        Element::Db => "Dubnium",
        Element::Sg => "Seaborgium",
        Element::Bh => "Bohrium",
        Element::Hs => "Hassium",
        Element::Mt => "Meitnerium",
        Element::Ds => "Darmstadtium",
        Element::Rg => "Roentgenium",
        Element::Cn => "CnCopernicium",
        Element::Nh => "Nihonium",
        Element::Fl => "Flerovium",
        Element::Mc => "Moscovium",
        Element::Lv => "Livermorium",
        Element::Ts => "Tennessine",
        Element::Og => "Oganesson",
    })
}

fn from(string: String) -> Option<Element> {
    match string.as_str() {
        "Hydrogen" => Some(Element::H),
        "Helium" => Some(Element::He),
        "Lithium" => Some(Element::Li),
        "Beryllium" => Some(Element::Be),
        "Boron" => Some(Element::B),
        "Carbon" => Some(Element::C),
        "Nitrogen" => Some(Element::N),
        "Oxygen" => Some(Element::O),
        "Fluorine" => Some(Element::F),
        "Neon" => Some(Element::Ne),
        "Sodium" => Some(Element::Na),
        "Magnesium" => Some(Element::Mg),
        "Aluminum" => Some(Element::Al),
        "Silicon" => Some(Element::Si),
        "Phosphorus" => Some(Element::P),
        "Sulfur" => Some(Element::S),
        "Chlorine" => Some(Element::Cl),
        "Argon" => Some(Element::Ar),
        "Potassium" => Some(Element::K),
        "Calcium" => Some(Element::Ca),
        "Scandium" => Some(Element::Sc),
        "Titanium" => Some(Element::Ti),
        "Vanadium" => Some(Element::V),
        "Chromium" => Some(Element::Cr),
        "Manganese" => Some(Element::Mn),
        "Iron" => Some(Element::Fe),
        "Cobalt" => Some(Element::Co),
        "Nickel" => Some(Element::Ni),
        "Copper" => Some(Element::Cu),
        "Zinc" => Some(Element::Zn),
        "Gallium" => Some(Element::Ga),
        "Germanium" => Some(Element::Ge),
        "Arsenic" => Some(Element::As),
        "Selenium" => Some(Element::Se),
        "Bromine" => Some(Element::Br),
        "Krypton" => Some(Element::Kr),
        "Rubidium" => Some(Element::Rb),
        "Strontium" => Some(Element::Sr),
        "Yttrium" => Some(Element::Y),
        "Zirconium" => Some(Element::Zr),
        "Niobium" => Some(Element::Nb),
        "Molybdenum" => Some(Element::Mo),
        "Technetium" => Some(Element::Tc),
        "Ruthenium" => Some(Element::Ru),
        "Rhodium" => Some(Element::Rh),
        "Palladium" => Some(Element::Pd),
        "Silver" => Some(Element::Ag),
        "Cadmium" => Some(Element::Cd),
        "Indium" => Some(Element::In),
        "Tin" => Some(Element::Sn),
        "Antimony" => Some(Element::Sb),
        "Tellurium" => Some(Element::Te),
        "Iodine" => Some(Element::I),
        "Xenon" => Some(Element::Xe),
        "Cesium" => Some(Element::Cs),
        "Barium" => Some(Element::Ba),
        "Lanthanum" => Some(Element::La),
        "Cerium" => Some(Element::Ce),
        "Praseodymium" => Some(Element::Pr),
        "Neodymium" => Some(Element::Nd),
        "Promethium" => Some(Element::Pm),
        "Samarium" => Some(Element::Sm),
        "Europium" => Some(Element::Eu),
        "Gadolinium" => Some(Element::Gd),
        "Terbium" => Some(Element::Tb),
        "Dysprosium" => Some(Element::Dy),
        "Holmium" => Some(Element::Ho),
        "Erbium" => Some(Element::Er),
        "Thulium" => Some(Element::Tm),
        "Ytterbium" => Some(Element::Yb),
        "Lutetium" => Some(Element::Lu),
        "Hafnium" => Some(Element::Hf),
        "Tantalum" => Some(Element::Ta),
        "Wolfram" => Some(Element::W),
        "Rhenium" => Some(Element::Re),
        "Osmium" => Some(Element::Os),
        "Iridium" => Some(Element::Ir),
        "Platinum" => Some(Element::Pt),
        "Gold" => Some(Element::Au),
        "Mercury" => Some(Element::Hg),
        "Thallium" => Some(Element::Tl),
        "Lead" => Some(Element::Pb),
        "Bismuth" => Some(Element::Bi),
        "Polonium" => Some(Element::Po),
        "Astatine" => Some(Element::At),
        "Radon" => Some(Element::Rn),
        "Francium" => Some(Element::Fr),
        "Radium" => Some(Element::Ra),
        "Actinium" => Some(Element::Ac),
        "Thorium" => Some(Element::Th),
        "Protactinium" => Some(Element::Pa),
        "Uranium" => Some(Element::U),
        "Neptunium" => Some(Element::Np),
        "Plutonium" => Some(Element::Pu),
        "Americium" => Some(Element::Am),
        "Curium" => Some(Element::Cm),
        "Berkelium" => Some(Element::Bk),
        "Californium" => Some(Element::Cf),
        "Einsteinium" => Some(Element::Es),
        "Fermium" => Some(Element::Fm),
        "Mendelevium" => Some(Element::Md),
        "Nobelium" => Some(Element::No),
        "Lawrencium" => Some(Element::Lr),
        "Rutherfordium" => Some(Element::Rf),
        "Dubnium" => Some(Element::Db),
        "Seaborgium" => Some(Element::Sg),
        "Bohrium" => Some(Element::Bh),
        "Hassium" => Some(Element::Hs),
        "Meitnerium" => Some(Element::Mt),
        "Darmstadtium" => Some(Element::Ds),
        "Roentgenium" => Some(Element::Rg),
        "CnCopernicium" => Some(Element::Cn),
        "Nihonium" => Some(Element::Nh),
        "Flerovium" => Some(Element::Fl),
        "Moscovium" => Some(Element::Mc),
        "Livermorium" => Some(Element::Lv),
        "Tennessine" => Some(Element::Ts),
        "Oganesson" => Some(Element::Og),
        _ => None,
    }
}
