pub struct Element {
    name: String,
    symbol: Symbol,
    atomic_number: u32,
    atomic_mass: f32,
}
impl Element {
    pub fn from(string: String) -> Result<Element, &'static str> {
        match string.to_lowercase().as_str() {
            "hydrogen" => Ok(Element {
                atomic_number: 1,
                name: String::from("Hydrogen"),
                symbol: Symbol::H,
                atomic_mass: 1.007,
            }),
            "helium" => Ok(Element {
                atomic_number: 2,
                name: String::from("Helium"),
                symbol: Symbol::He,
                atomic_mass: 4.002,
            }),
            "lithium" => Ok(Element {
                atomic_number: 3,
                name: String::from("Lithium"),
                symbol: Symbol::Li,
                atomic_mass: 6.941,
            }),
            "beryllium" => Ok(Element {
                atomic_number: 4,
                name: String::from("Beryllium"),
                symbol: Symbol::Be,
                atomic_mass: 9.012,
            }),
            "boron" => Ok(Element {
                atomic_number: 5,
                name: String::from("Boron"),
                symbol: Symbol::B,
                atomic_mass: 10.811,
            }),
            "carbon" => Ok(Element {
                atomic_number: 6,
                name: String::from("Carbon"),
                symbol: Symbol::C,
                atomic_mass: 12.011,
            }),
            "nitrogen" => Ok(Element {
                atomic_number: 7,
                name: String::from("Nitrogen"),
                symbol: Symbol::N,
                atomic_mass: 14.007,
            }),
            "oxygen" => Ok(Element {
                atomic_number: 8,
                name: String::from("Oxygen"),
                symbol: Symbol::O,
                atomic_mass: 15.999,
            }),
            "fluorine" => Ok(Element {
                atomic_number: 9,
                name: String::from("Fluorine"),
                symbol: Symbol::F,
                atomic_mass: 18.998,
            }),
            "neon" => Ok(Element {
                atomic_number: 10,
                name: String::from("Neon"),
                symbol: Symbol::Ne,
                atomic_mass: 20.18,
            }),
            "sodium" => Ok(Element {
                atomic_number: 11,
                name: String::from("Sodium"),
                symbol: Symbol::Na,
                atomic_mass: 22.99,
            }),
            "magnesium" => Ok(Element {
                atomic_number: 12,
                name: String::from("Magnesium"),
                symbol: Symbol::Mg,
                atomic_mass: 24.305,
            }),
            "aluminum" => Ok(Element {
                atomic_number: 13,
                name: String::from("Aluminum"),
                symbol: Symbol::Al,
                atomic_mass: 26.982,
            }),
            "silicon" => Ok(Element {
                atomic_number: 14,
                name: String::from("Silicon"),
                symbol: Symbol::Si,
                atomic_mass: 28.086,
            }),
            "phosphorus" => Ok(Element {
                atomic_number: 15,
                name: String::from("Phosphorus"),
                symbol: Symbol::P,
                atomic_mass: 30.974,
            }),
            "sulfur" => Ok(Element {
                atomic_number: 16,
                name: String::from("Sulfur"),
                symbol: Symbol::S,
                atomic_mass: 32.065,
            }),
            "chlorine" => Ok(Element {
                atomic_number: 17,
                name: String::from("Chlorine"),
                symbol: Symbol::Cl,
                atomic_mass: 35.453,
            }),
            "argon" => Ok(Element {
                atomic_number: 18,
                name: String::from("Argon"),
                symbol: Symbol::Ar,
                atomic_mass: 39.948,
            }),
            "potassium" => Ok(Element {
                atomic_number: 19,
                name: String::from("Potassium"),
                symbol: Symbol::K,
                atomic_mass: 39.098,
            }),
            "calcium" => Ok(Element {
                atomic_number: 20,
                name: String::from("Calcium"),
                symbol: Symbol::Ca,
                atomic_mass: 40.078,
            }),
            "scandium" => Ok(Element {
                atomic_number: 21,
                name: String::from("Scandium"),
                symbol: Symbol::Sc,
                atomic_mass: 44.956,
            }),
            "titanium" => Ok(Element {
                atomic_number: 22,
                name: String::from("Titanium"),
                symbol: Symbol::Ti,
                atomic_mass: 47.867,
            }),
            "vanadium" => Ok(Element {
                atomic_number: 23,
                name: String::from("Vanadium"),
                symbol: Symbol::V,
                atomic_mass: 50.942,
            }),
            "chromium" => Ok(Element {
                atomic_number: 24,
                name: String::from("Chromium"),
                symbol: Symbol::Cr,
                atomic_mass: 51.996,
            }),
            "manganese" => Ok(Element {
                atomic_number: 25,
                name: String::from("Manganese"),
                symbol: Symbol::Mn,
                atomic_mass: 54.938,
            }),
            "iron" => Ok(Element {
                atomic_number: 26,
                name: String::from("Iron"),
                symbol: Symbol::Fe,
                atomic_mass: 55.845,
            }),
            "cobalt" => Ok(Element {
                atomic_number: 27,
                name: String::from("Cobalt"),
                symbol: Symbol::Co,
                atomic_mass: 58.933,
            }),
            "nickel" => Ok(Element {
                atomic_number: 28,
                name: String::from("Nickel"),
                symbol: Symbol::Ni,
                atomic_mass: 58.693,
            }),
            "copper" => Ok(Element {
                atomic_number: 29,
                name: String::from("Copper"),
                symbol: Symbol::Cu,
                atomic_mass: 63.546,
            }),
            "zinc" => Ok(Element {
                atomic_number: 30,
                name: String::from("Zinc"),
                symbol: Symbol::Zn,
                atomic_mass: 65.38,
            }),
            "gallium" => Ok(Element {
                atomic_number: 31,
                name: String::from("Gallium"),
                symbol: Symbol::Ga,
                atomic_mass: 69.723,
            }),
            "germanium" => Ok(Element {
                atomic_number: 32,
                name: String::from("Germanium"),
                symbol: Symbol::Ge,
                atomic_mass: 72.64,
            }),
            "arsenic" => Ok(Element {
                atomic_number: 33,
                name: String::from("Arsenic"),
                symbol: Symbol::As,
                atomic_mass: 74.922,
            }),
            "selenium" => Ok(Element {
                atomic_number: 34,
                name: String::from("Selenium"),
                symbol: Symbol::Se,
                atomic_mass: 78.96,
            }),
            "bromine" => Ok(Element {
                atomic_number: 35,
                name: String::from("Bromine"),
                symbol: Symbol::Br,
                atomic_mass: 79.904,
            }),
            "krypton" => Ok(Element {
                atomic_number: 36,
                name: String::from("Krypton"),
                symbol: Symbol::Kr,
                atomic_mass: 83.798,
            }),
            "rubidium" => Ok(Element {
                atomic_number: 37,
                name: String::from("Rubidium"),
                symbol: Symbol::Rb,
                atomic_mass: 85.468,
            }),
            "strontium" => Ok(Element {
                atomic_number: 38,
                name: String::from("Strontium"),
                symbol: Symbol::Sr,
                atomic_mass: 87.62,
            }),
            "yttrium" => Ok(Element {
                atomic_number: 39,
                name: String::from("Yttrium"),
                symbol: Symbol::Y,
                atomic_mass: 88.906,
            }),
            "zirconium" => Ok(Element {
                atomic_number: 40,
                name: String::from("Zirconium"),
                symbol: Symbol::Zr,
                atomic_mass: 91.224,
            }),
            "niobium" => Ok(Element {
                atomic_number: 41,
                name: String::from("Niobium"),
                symbol: Symbol::Nb,
                atomic_mass: 92.906,
            }),
            "molybdenum" => Ok(Element {
                atomic_number: 42,
                name: String::from("Molybdenum"),
                symbol: Symbol::Mo,
                atomic_mass: 95.96,
            }),
            "technetium" => Ok(Element {
                atomic_number: 43,
                name: String::from("Technetium"),
                symbol: Symbol::Tc,
                atomic_mass: 98.,
            }),
            "ruthenium" => Ok(Element {
                atomic_number: 44,
                name: String::from("Ruthenium"),
                symbol: Symbol::Ru,
                atomic_mass: 101.07,
            }),
            "rhodium" => Ok(Element {
                atomic_number: 45,
                name: String::from("Rhodium"),
                symbol: Symbol::Rh,
                atomic_mass: 102.906,
            }),
            "palladium" => Ok(Element {
                atomic_number: 46,
                name: String::from("Palladium"),
                symbol: Symbol::Pd,
                atomic_mass: 106.42,
            }),
            "silver" => Ok(Element {
                atomic_number: 47,
                name: String::from("Silver"),
                symbol: Symbol::Ag,
                atomic_mass: 107.868,
            }),
            "cadmium" => Ok(Element {
                atomic_number: 48,
                name: String::from("Cadmium"),
                symbol: Symbol::Cd,
                atomic_mass: 112.411,
            }),
            "indium" => Ok(Element {
                atomic_number: 49,
                name: String::from("Indium"),
                symbol: Symbol::In,
                atomic_mass: 114.818,
            }),
            "tin" => Ok(Element {
                atomic_number: 50,
                name: String::from("Tin"),
                symbol: Symbol::Sn,
                atomic_mass: 118.71,
            }),
            "antimony" => Ok(Element {
                atomic_number: 51,
                name: String::from("Antimony"),
                symbol: Symbol::Sb,
                atomic_mass: 121.76,
            }),
            "tellurium" => Ok(Element {
                atomic_number: 52,
                name: String::from("Tellurium"),
                symbol: Symbol::Te,
                atomic_mass: 127.6,
            }),
            "iodine" => Ok(Element {
                atomic_number: 53,
                name: String::from("Iodine"),
                symbol: Symbol::I,
                atomic_mass: 126.904,
            }),
            "xenon" => Ok(Element {
                atomic_number: 54,
                name: String::from("Xenon"),
                symbol: Symbol::Xe,
                atomic_mass: 131.293,
            }),
            "cesium" => Ok(Element {
                atomic_number: 55,
                name: String::from("Cesium"),
                symbol: Symbol::Cs,
                atomic_mass: 132.905,
            }),
            "barium" => Ok(Element {
                atomic_number: 56,
                name: String::from("Barium"),
                symbol: Symbol::Ba,
                atomic_mass: 137.327,
            }),
            "lanthanum" => Ok(Element {
                atomic_number: 57,
                name: String::from("Lanthanum"),
                symbol: Symbol::La,
                atomic_mass: 138.905,
            }),
            "cerium" => Ok(Element {
                atomic_number: 58,
                name: String::from("Cerium"),
                symbol: Symbol::Ce,
                atomic_mass: 140.116,
            }),
            "praseodymium" => Ok(Element {
                atomic_number: 59,
                name: String::from("Praseodymium"),
                symbol: Symbol::Pr,
                atomic_mass: 140.908,
            }),
            "neodymium" => Ok(Element {
                atomic_number: 60,
                name: String::from("Neodymium"),
                symbol: Symbol::Nd,
                atomic_mass: 144.242,
            }),
            "promethium" => Ok(Element {
                atomic_number: 61,
                name: String::from("Promethium"),
                symbol: Symbol::Pm,
                atomic_mass: 145.,
            }),
            "samarium" => Ok(Element {
                atomic_number: 62,
                name: String::from("Samarium"),
                symbol: Symbol::Sm,
                atomic_mass: 150.36,
            }),
            "europium" => Ok(Element {
                atomic_number: 63,
                name: String::from("Europium"),
                symbol: Symbol::Eu,
                atomic_mass: 151.964,
            }),
            "gadolinium" => Ok(Element {
                atomic_number: 64,
                name: String::from("Gadolinium"),
                symbol: Symbol::Gd,
                atomic_mass: 157.25,
            }),
            "terbium" => Ok(Element {
                atomic_number: 65,
                name: String::from("Terbium"),
                symbol: Symbol::Tb,
                atomic_mass: 158.925,
            }),
            "dysprosium" => Ok(Element {
                atomic_number: 66,
                name: String::from("Dysprosium"),
                symbol: Symbol::Dy,
                atomic_mass: 162.5,
            }),
            "holmium" => Ok(Element {
                atomic_number: 67,
                name: String::from("Holmium"),
                symbol: Symbol::Ho,
                atomic_mass: 164.93,
            }),
            "erbium" => Ok(Element {
                atomic_number: 68,
                name: String::from("Erbium"),
                symbol: Symbol::Er,
                atomic_mass: 167.259,
            }),
            "thulium" => Ok(Element {
                atomic_number: 69,
                name: String::from("Thulium"),
                symbol: Symbol::Tm,
                atomic_mass: 168.934,
            }),
            "ytterbium" => Ok(Element {
                atomic_number: 70,
                name: String::from("Ytterbium"),
                symbol: Symbol::Yb,
                atomic_mass: 173.054,
            }),
            "lutetium" => Ok(Element {
                atomic_number: 71,
                name: String::from("Lutetium"),
                symbol: Symbol::Lu,
                atomic_mass: 174.967,
            }),
            "hafnium" => Ok(Element {
                atomic_number: 72,
                name: String::from("Hafnium"),
                symbol: Symbol::Hf,
                atomic_mass: 178.49,
            }),
            "tantalum" => Ok(Element {
                atomic_number: 73,
                name: String::from("Tantalum"),
                symbol: Symbol::Ta,
                atomic_mass: 180.948,
            }),
            "wolfram" => Ok(Element {
                atomic_number: 74,
                name: String::from("Wolfram"),
                symbol: Symbol::W,
                atomic_mass: 183.84,
            }),
            "rhenium" => Ok(Element {
                atomic_number: 75,
                name: String::from("Rhenium"),
                symbol: Symbol::Re,
                atomic_mass: 186.207,
            }),
            "osmium" => Ok(Element {
                atomic_number: 76,
                name: String::from("Osmium"),
                symbol: Symbol::Os,
                atomic_mass: 190.23,
            }),
            "iridium" => Ok(Element {
                atomic_number: 77,
                name: String::from("Iridium"),
                symbol: Symbol::Ir,
                atomic_mass: 192.217,
            }),
            "platinum" => Ok(Element {
                atomic_number: 78,
                name: String::from("Platinum"),
                symbol: Symbol::Pt,
                atomic_mass: 195.084,
            }),
            "gold" => Ok(Element {
                atomic_number: 79,
                name: String::from("Gold"),
                symbol: Symbol::Au,
                atomic_mass: 196.967,
            }),
            "mercury" => Ok(Element {
                atomic_number: 80,
                name: String::from("Mercury"),
                symbol: Symbol::Hg,
                atomic_mass: 200.59,
            }),
            "thallium" => Ok(Element {
                atomic_number: 81,
                name: String::from("Thallium"),
                symbol: Symbol::Tl,
                atomic_mass: 204.383,
            }),
            "lead" => Ok(Element {
                atomic_number: 82,
                name: String::from("Lead"),
                symbol: Symbol::Pb,
                atomic_mass: 207.2,
            }),
            "bismuth" => Ok(Element {
                atomic_number: 83,
                name: String::from("Bismuth"),
                symbol: Symbol::Bi,
                atomic_mass: 208.98,
            }),
            "polonium" => Ok(Element {
                atomic_number: 84,
                name: String::from("Polonium"),
                symbol: Symbol::Po,
                atomic_mass: 210.,
            }),
            "astatine" => Ok(Element {
                atomic_number: 85,
                name: String::from("Astatine"),
                symbol: Symbol::At,
                atomic_mass: 210.,
            }),
            "radon" => Ok(Element {
                atomic_number: 86,
                name: String::from("Radon"),
                symbol: Symbol::Rn,
                atomic_mass: 222.,
            }),
            "francium" => Ok(Element {
                atomic_number: 87,
                name: String::from("Francium"),
                symbol: Symbol::Fr,
                atomic_mass: 223.,
            }),
            "radium" => Ok(Element {
                atomic_number: 88,
                name: String::from("Radium"),
                symbol: Symbol::Ra,
                atomic_mass: 226.,
            }),
            "actinium" => Ok(Element {
                atomic_number: 89,
                name: String::from("Actinium"),
                symbol: Symbol::Ac,
                atomic_mass: 227.,
            }),
            "thorium" => Ok(Element {
                atomic_number: 90,
                name: String::from("Thorium"),
                symbol: Symbol::Th,
                atomic_mass: 232.038,
            }),
            "protactinium" => Ok(Element {
                atomic_number: 91,
                name: String::from("Protactinium"),
                symbol: Symbol::Pa,
                atomic_mass: 231.036,
            }),
            "uranium" => Ok(Element {
                atomic_number: 92,
                name: String::from("Uranium"),
                symbol: Symbol::U,
                atomic_mass: 238.029,
            }),
            "neptunium" => Ok(Element {
                atomic_number: 93,
                name: String::from("Neptunium"),
                symbol: Symbol::Np,
                atomic_mass: 237.,
            }),
            "plutonium" => Ok(Element {
                atomic_number: 94,
                name: String::from("Plutonium"),
                symbol: Symbol::Pu,
                atomic_mass: 244.,
            }),
            "americium" => Ok(Element {
                atomic_number: 95,
                name: String::from("Americium"),
                symbol: Symbol::Am,
                atomic_mass: 243.,
            }),
            "curium" => Ok(Element {
                atomic_number: 96,
                name: String::from("Curium"),
                symbol: Symbol::Cm,
                atomic_mass: 247.,
            }),
            "berkelium" => Ok(Element {
                atomic_number: 97,
                name: String::from("Berkelium"),
                symbol: Symbol::Bk,
                atomic_mass: 247.,
            }),
            "californium" => Ok(Element {
                atomic_number: 98,
                name: String::from("Californium"),
                symbol: Symbol::Cf,
                atomic_mass: 251.,
            }),
            "einsteinium" => Ok(Element {
                atomic_number: 99,
                name: String::from("Einsteinium"),
                symbol: Symbol::Es,
                atomic_mass: 252.,
            }),
            "fermium" => Ok(Element {
                atomic_number: 100,
                name: String::from("Fermium"),
                symbol: Symbol::Fm,
                atomic_mass: 257.,
            }),
            "mendelevium" => Ok(Element {
                atomic_number: 101,
                name: String::from("Mendelevium"),
                symbol: Symbol::Md,
                atomic_mass: 258.,
            }),
            "nobelium" => Ok(Element {
                atomic_number: 102,
                name: String::from("Nobelium"),
                symbol: Symbol::No,
                atomic_mass: 259.,
            }),
            "lawrencium" => Ok(Element {
                atomic_number: 103,
                name: String::from("Lawrencium"),
                symbol: Symbol::Lr,
                atomic_mass: 262.,
            }),
            "rutherfordium" => Ok(Element {
                atomic_number: 104,
                name: String::from("Rutherfordium"),
                symbol: Symbol::Rf,
                atomic_mass: 261.,
            }),
            "dubnium" => Ok(Element {
                atomic_number: 105,
                name: String::from("Dubnium"),
                symbol: Symbol::Db,
                atomic_mass: 262.,
            }),
            "seaborgium" => Ok(Element {
                atomic_number: 106,
                name: String::from("Seaborgium"),
                symbol: Symbol::Sg,
                atomic_mass: 266.,
            }),
            "bohrium" => Ok(Element {
                atomic_number: 107,
                name: String::from("Bohrium"),
                symbol: Symbol::Bh,
                atomic_mass: 264.,
            }),
            "hassium" => Ok(Element {
                atomic_number: 108,
                name: String::from("Hassium"),
                symbol: Symbol::Hs,
                atomic_mass: 267.,
            }),
            "meitnerium" => Ok(Element {
                atomic_number: 109,
                name: String::from("Meitnerium"),
                symbol: Symbol::Mt,
                atomic_mass: 268.,
            }),
            "darmstadtium " => Ok(Element {
                atomic_number: 110,
                name: String::from("Darmstadtium "),
                symbol: Symbol::Ds,
                atomic_mass: 271.,
            }),
            "roentgenium " => Ok(Element {
                atomic_number: 111,
                name: String::from("Roentgenium "),
                symbol: Symbol::Rg,
                atomic_mass: 272.,
            }),
            "copernicium " => Ok(Element {
                atomic_number: 112,
                name: String::from("Copernicium "),
                symbol: Symbol::Cn,
                atomic_mass: 285.,
            }),
            "nihonium" => Ok(Element {
                atomic_number: 113,
                name: String::from("Nihonium"),
                symbol: Symbol::Nh,
                atomic_mass: 284.,
            }),
            "flerovium" => Ok(Element {
                atomic_number: 114,
                name: String::from("Flerovium"),
                symbol: Symbol::Fl,
                atomic_mass: 289.,
            }),
            "moscovium" => Ok(Element {
                atomic_number: 115,
                name: String::from("Moscovium"),
                symbol: Symbol::Mc,
                atomic_mass: 288.,
            }),
            "livermorium" => Ok(Element {
                atomic_number: 116,
                name: String::from("Livermorium"),
                symbol: Symbol::Lv,
                atomic_mass: 292.,
            }),
            "tennessine" => Ok(Element {
                atomic_number: 117,
                name: String::from("Tennessine"),
                symbol: Symbol::Ts,
                atomic_mass: 295.,
            }),
            "oganesson" => Ok(Element {
                atomic_number: 118,
                name: String::from("Oganesson"),
                symbol: Symbol::Og,
                atomic_mass: 294.,
            }),
            _ => Err("Error"),
        }
    }
    pub fn to_string(element: Element) -> String {
        element.name
    }
}
pub enum Symbol {
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og,
}
