pub enum Element {
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og,
}
pub fn to_string(element: Element) -> String {
    String::from(match element {
        Element::H => "Hydrogen",
        Element::He => "Helium",
        Element::Li => "Lithium",
        Element::Be => "Beryllium",
        Element::B => "Boron",
        Element::C => "Carbon",
        Element::N => "Nitrogen",
        Element::O => "Oxygen",
        Element::F => "Fluorine",
        Element::Ne => "Neon",
        Element::Na => "Sodium",
        Element::Mg => "Magnesium",
        Element::Al => "Aluminum",
        Element::Si => "Silicon",
        Element::P => "Phosphorus",
        Element::S => "Sulfur",
        Element::Cl => "Chlorine",
        Element::Ar => "Argon",
        Element::K => "Potassium",
        Element::Ca => "Calcium",
        Element::Sc => "Scandium",
        Element::Ti => "Titanium",
        Element::V => "Vanadium",
        Element::Cr => "Chromium",
        Element::Mn => "Manganese",
        Element::Fe => "Iron",
        Element::Co => "Cobalt",
        Element::Ni => "Nickel",
        Element::Cu => "Copper",
        Element::Zn => "Zinc",
        Element::Ga => "Gallium",
        Element::Ge => "Germanium",
        Element::As => "Arsenic",
        Element::Se => "Selenium",
        Element::Br => "Bromine",
        Element::Kr => "Krypton",
        Element::Rb => "Rubidium",
        Element::Sr => "Strontium",
        Element::Y => "Yttrium",
        Element::Zr => "Zirconium",
        Element::Nb => "Niobium",
        Element::Mo => "Molybdenum",
        Element::Tc => "Technetium",
        Element::Ru => "Ruthenium",
        Element::Rh => "Rhodium",
        Element::Pd => "Palladium",
        Element::Ag => "Silver",
        Element::Cd => "Cadmium",
        Element::In => "Indium",
        Element::Sn => "Tin",
        Element::Sb => "Antimony",
        Element::Te => "Tellurium",
        Element::I => "Iodine",
        Element::Xe => "Xenon",
        Element::Cs => "Cesium",
        Element::Ba => "Barium",
        Element::La => "Lanthanum",
        Element::Ce => "Cerium",
        Element::Pr => "Praseodymium",
        Element::Nd => "Neodymium",
        Element::Pm => "Promethium",
        Element::Sm => "Samarium",
        Element::Eu => "Europium",
        Element::Gd => "Gadolinium",
        Element::Tb => "Terbium",
        Element::Dy => "Dysprosium",
        Element::Ho => "Holmium",
        Element::Er => "Erbium",
        Element::Tm => "Thulium",
        Element::Yb => "Ytterbium",
        Element::Lu => "Lutetium",
        Element::Hf => "Hafnium",
        Element::Ta => "Tantalum",
        Element::W => "Wolfram",
        Element::Re => "Rhenium",
        Element::Os => "Osmium",
        Element::Ir => "Iridium",
        Element::Pt => "Platinum",
        Element::Au => "Gold",
        Element::Hg => "Mercury",
        Element::Tl => "Thallium",
        Element::Pb => "Lead",
        Element::Bi => "Bismuth",
        Element::Po => "Polonium",
        Element::At => "Astatine",
        Element::Rn => "Radon",
        Element::Fr => "Francium",
        Element::Ra => "Radium",
        Element::Ac => "Actinium",
        Element::Th => "Thorium",
        Element::Pa => "Protactinium",
        Element::U => "Uranium",
        Element::Np => "Neptunium",
        Element::Pu => "Plutonium",
        Element::Am => "Americium",
        Element::Cm => "Curium",
        Element::Bk => "Berkelium",
        Element::Cf => "Californium",
        Element::Es => "Einsteinium",
        Element::Fm => "Fermium",
        Element::Md => "Mendelevium",
        Element::No => "Nobelium",
        Element::Lr => "Lawrencium",
        Element::Rf => "Rutherfordium",
        Element::Db => "Dubnium",
        Element::Sg => "Seaborgium",
        Element::Bh => "Bohrium",
        Element::Hs => "Hassium",
        Element::Mt => "Meitnerium",
        Element::Ds => "Darmstadtium",
        Element::Rg => "Roentgenium",
        Element::Cn => "CnCopernicium",
        Element::Nh => "Nihonium",
        Element::Fl => "Flerovium",
        Element::Mc => "Moscovium",
        Element::Lv => "Livermorium",
        Element::Ts => "Tennessine",
        Element::Og => "Oganesson",
    })
}

pub fn from(string: String) -> Option<Element> {
    match string.to_lowercase().as_str() {
        "hydrogen" => Some(Element::H),
        "helium" => Some(Element::He),
        "lithium" => Some(Element::Li),
        "beryllium" => Some(Element::Be),
        "boron" => Some(Element::B),
        "carbon" => Some(Element::C),
        "nitrogen" => Some(Element::N),
        "oxygen" => Some(Element::O),
        "fluorine" => Some(Element::F),
        "neon" => Some(Element::Ne),
        "sodium" => Some(Element::Na),
        "magnesium" => Some(Element::Mg),
        "aluminum" => Some(Element::Al),
        "silicon" => Some(Element::Si),
        "phosphorus" => Some(Element::P),
        "sulfur" => Some(Element::S),
        "chlorine" => Some(Element::Cl),
        "argon" => Some(Element::Ar),
        "potassium" => Some(Element::K),
        "calcium" => Some(Element::Ca),
        "scandium" => Some(Element::Sc),
        "titanium" => Some(Element::Ti),
        "vanadium" => Some(Element::V),
        "chromium" => Some(Element::Cr),
        "manganese" => Some(Element::Mn),
        "iron" => Some(Element::Fe),
        "cobalt" => Some(Element::Co),
        "nickel" => Some(Element::Ni),
        "copper" => Some(Element::Cu),
        "zinc" => Some(Element::Zn),
        "gallium" => Some(Element::Ga),
        "germanium" => Some(Element::Ge),
        "arsenic" => Some(Element::As),
        "selenium" => Some(Element::Se),
        "bromine" => Some(Element::Br),
        "krypton" => Some(Element::Kr),
        "rubidium" => Some(Element::Rb),
        "strontium" => Some(Element::Sr),
        "yttrium" => Some(Element::Y),
        "zirconium" => Some(Element::Zr),
        "niobium" => Some(Element::Nb),
        "molybdenum" => Some(Element::Mo),
        "technetium" => Some(Element::Tc),
        "ruthenium" => Some(Element::Ru),
        "rhodium" => Some(Element::Rh),
        "palladium" => Some(Element::Pd),
        "silver" => Some(Element::Ag),
        "cadmium" => Some(Element::Cd),
        "indium" => Some(Element::In),
        "tin" => Some(Element::Sn),
        "antimony" => Some(Element::Sb),
        "tellurium" => Some(Element::Te),
        "iodine" => Some(Element::I),
        "xenon" => Some(Element::Xe),
        "cesium" => Some(Element::Cs),
        "barium" => Some(Element::Ba),
        "lanthanum" => Some(Element::La),
        "cerium" => Some(Element::Ce),
        "praseodymium" => Some(Element::Pr),
        "neodymium" => Some(Element::Nd),
        "promethium" => Some(Element::Pm),
        "samarium" => Some(Element::Sm),
        "europium" => Some(Element::Eu),
        "gadolinium" => Some(Element::Gd),
        "terbium" => Some(Element::Tb),
        "dysprosium" => Some(Element::Dy),
        "holmium" => Some(Element::Ho),
        "erbium" => Some(Element::Er),
        "thulium" => Some(Element::Tm),
        "ytterbium" => Some(Element::Yb),
        "lutetium" => Some(Element::Lu),
        "hafnium" => Some(Element::Hf),
        "tantalum" => Some(Element::Ta),
        "wolfram" => Some(Element::W),
        "rhenium" => Some(Element::Re),
        "osmium" => Some(Element::Os),
        "iridium" => Some(Element::Ir),
        "platinum" => Some(Element::Pt),
        "gold" => Some(Element::Au),
        "mercury" => Some(Element::Hg),
        "thallium" => Some(Element::Tl),
        "lead" => Some(Element::Pb),
        "bismuth" => Some(Element::Bi),
        "polonium" => Some(Element::Po),
        "astatine" => Some(Element::At),
        "radon" => Some(Element::Rn),
        "francium" => Some(Element::Fr),
        "radium" => Some(Element::Ra),
        "actinium" => Some(Element::Ac),
        "thorium" => Some(Element::Th),
        "protactinium" => Some(Element::Pa),
        "uranium" => Some(Element::U),
        "neptunium" => Some(Element::Np),
        "plutonium" => Some(Element::Pu),
        "americium" => Some(Element::Am),
        "curium" => Some(Element::Cm),
        "berkelium" => Some(Element::Bk),
        "californium" => Some(Element::Cf),
        "einsteinium" => Some(Element::Es),
        "fermium" => Some(Element::Fm),
        "mendelevium" => Some(Element::Md),
        "nobelium" => Some(Element::No),
        "lawrencium" => Some(Element::Lr),
        "rutherfordium" => Some(Element::Rf),
        "dubnium" => Some(Element::Db),
        "seaborgium" => Some(Element::Sg),
        "bohrium" => Some(Element::Bh),
        "hassium" => Some(Element::Hs),
        "meitnerium" => Some(Element::Mt),
        "darmstadtium" => Some(Element::Ds),
        "roentgenium" => Some(Element::Rg),
        "copernicium" => Some(Element::Cn),
        "nihonium" => Some(Element::Nh),
        "flerovium" => Some(Element::Fl),
        "moscovium" => Some(Element::Mc),
        "livermorium" => Some(Element::Lv),
        "tennessine" => Some(Element::Ts),
        "oganesson" => Some(Element::Og),
        _ => None,
    }
}
